# Generated by Django 4.2.9 on 2024-01-07 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewcal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('crew', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewcal.job')),
            ],
        ),
    ]
