# Generated by Django 4.2.9 on 2024-01-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewcal', '0003_alter_dateentry_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['company', 'workgroup'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workgroup',
            field=models.CharField(default='Default Workgroup', max_length=100),
        ),
    ]
