# Generated by Django 4.2.9 on 2024-01-14 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewcal', '0004_alter_userprofile_options_userprofile_workgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='workgroup',
        ),
        migrations.CreateModel(
            name='CompanyWorkgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewcal.company')),
                ('workgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewcal.workgroup')),
            ],
            options={
                'unique_together': {('company', 'workgroup')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_workgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crewcal.companyworkgroup'),
            preserve_default=False,
        ),
    ]
