# Generated by Django 4.2.9 on 2024-01-14 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewcal', '0005_company_workgroup_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_workgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crewcal.companyworkgroup'),
            preserve_default=False,
        ),
    ]
