# Generated by Django 4.1 on 2024-05-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crewcal", "0006_job_company_workgroup"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dateentry",
            index=models.Index(fields=["date"], name="crewcal_dat_date_c4b5cf_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["name"], name="crewcal_job_name_337d1d_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["number"], name="crewcal_job_number_d5fcb6_idx"),
        ),
    ]
