# Generated by Django 5.0 on 2023-12-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('I', 'Injury'), ('H', 'Hazard'), ('V', 'Variation'), ('N', 'Nonconformance'), ('M', 'Improvement'), ('O', 'Other')], max_length=1)),
                ('incident_date', models.DateTimeField()),
                ('site', models.CharField(max_length=50)),
                ('date_reported', models.DateField(auto_now=True, null=True)),
                ('reported_by', models.CharField(max_length=50)),
                ('reported_to', models.CharField(max_length=50, null=True)),
                ('witness_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=300)),
                ('root_cause', models.CharField(max_length=300, null=True)),
                ('action_taken', models.CharField(max_length=300, null=True)),
                ('sign_off', models.CharField(max_length=50)),
                ('sign_off_date', models.DateField()),
            ],
        ),
    ]
