# Generated by Django 5.0 on 2023-12-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['incident_date']},
        ),
    ]
