# Generated by Django 5.0 on 2023-12-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_incidentreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['incident_date']},
        ),
    ]
